[tool.poetry]
name = "yc-scraper"
version = "0.1.0"
description = "YCombinator company director scraper"
authors = ["Alvaro Peña"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
